### PR TITLE
Rough english translation

### PR DESCRIPTION
**Pull request by DeathWrench**

### CODE REVIEW

**Comment by chuxiaaaa** [comment]
emmm,Why does the file "en_US1.Designer.cs" have an extra "1" at the end?

**Comment by DeathWrench** [comment]
It's just how Visual Studio created it, I fixed it though.

**Comment by chuxiaaaa** [comment]
Has the text display been tested and proven normal in the game?

**Comment by DeathWrench** [comment]
Looks fine to me 
image

**Comment by chuxiaaaa** [comment]
Thunderstore has uploaded the merged version.

**Pull request merged**
